### ISSUE TITLE
metro-react-native-babel-transformer needs to be replaced in RN 0.73

### ISSUE THREAD

**Issue by vonSchweeee** [kristerkari/react-native-svg-transformer#321] opened 2023-12-07 18:49 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg-transformer@1.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg-transformer/index.js b/node_modules/react-native-svg-transformer/index.js
index e07ebb6..4bee8c4 100644
--- a/node_modules/react-native-svg-transformer/index.js
+++ b/node_modules/react-native-svg-transformer/index.js
@@ -1,6 +1,6 @@
 const { resolveConfig, transform } = require("@svgr/core");
 const resolveConfigDir = require("path-dirname");
-const upstreamTransformer = require("metro-react-native-babel-transformer");
+const upstreamTransformer = require("@react-native/metro-babel-transformer");
 
 const defaultSVGRConfig = {
   native: true,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AndyS007** [comment] 2023-12-08 08:05
I encountered the same problem

**Comment by saoudnazir** [comment] 2023-12-08 09:53
Same issue

**Comment by chriszs** [comment] 2023-12-09 14:15
Dupe of #317

**Comment by kristerkari** [comment] 2023-12-11 16:38
I'm releasing a new version with a fix soon :)

**Comment by kristerkari** [comment] 2023-12-11 16:49
Thanks for reporting this, new version out:
https://github.com/kristerkari/react-native-svg-transformer/releases/tag/v1.2.0

**Comment by efstathiosntonas** [comment] 2024-01-09 15:20
@kristerkari this change creates issues for bare react-native projects using expo-modules-core. Been hunting this bug for 2 days 😓 

It was causing:

1. `Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.` and `Warning: React has detected a change in the order of Hooks called by XXXX` every time I added a hook in my code, upon fast-refresh it throwed this. 
2. Upon metro run it throwed this: `transform[stderr]: Missing transform.routerRoot option in Metro bundling request, falling back to `app` as routes directory.`

It drove me crazy to spot the issue and I went through a huge `package.json` git history. The eslint rule `react-hooks/rules-of-hooks` did not throw any errors, I do not call components as functions so I had to dig into `package.json` history and check all packages one by one. 

As a temp fix I made these changes: 

```diff
const upstreamTransformer = (() => {
  try {
    - return require("@expo/metro-config/babel-transformer");
    +  return require("@react-native/metro-babel-transformer");
  } catch (error) {
    try {
      return require("@react-native/metro-babel-transformer");
    } catch (error) {
      return require("metro-react-native-babel-transformer");
    }
  }
})(); 
```

**Comment by kristerkari** [comment] 2024-01-09 15:26
@efstathiosntonas Thanks for reporting! Would it be possible for you to create some kind of reproducible demo of the problem, like a new React Native project with only the required dependencies to trigger the errror?

I think that so far people have been using pure React Native or pure Expo projects, but not mixing them.

**Comment by efstathiosntonas** [comment] 2024-01-09 15:26
@kristerkari sure, let me give it a go.

**Comment by efstathiosntonas** [comment] 2024-01-09 16:27
@kristerkari here it is: https://github.com/efstathiosntonas/bare-react-native-expo-svg-transformer-issue

just comment and uncomment this line and hit save to trigger fast-refresh: 

https://github.com/efstathiosntonas/bare-react-native-expo-svg-transformer-issue/blob/5de38d169401fe32e952f2d1f2036181833458ad/App.tsx#L65

**Comment by kristerkari** [comment] 2024-03-09 21:57
@efstathiosntonas Hi again, I have been trying to think how to solve the problem that you have, and what I'm trying to figure out is how to detect if the project is a normal React Native project or an Expo project.

In your case it's a normal RN project, but it is using Expo, so it's a bit tricky to know. Not sure if there is a good way without adding some kind of option to the library to switch between Expo and React Native.

**Comment by Bardiamist** [comment] 2024-06-10 08:03
Same problem. I also use bare React native with expo.

**Comment by kristerkari** [comment] 2024-06-11 15:04
@Bardiamist I'm aware that this library does not currently support a React Native project that has some Expo modules added to it. I haven't yet found a way to automatically detect that kind of setup, so still the only way to fix it might be to introduce some kind of an option that would allow the user to override the default trasformer by choosing between React Native and Expo.

**Comment by kristerkari** [comment] 2024-07-07 16:26
Regarding React Native projects that happen to use some Expo dependencies, I have opened a PR #366 to add support for defining the transformer based on the project: 

```diff
-require.resolve("react-native-svg-transformer")
+require.resolve("react-native-svg-transformer/react-native")
```

This is only additional config, and won't need migration for existing projects.

Please let me know if you think that this is good appoarch to work around the problem.

**Closed** 2024-07-09 19:15 UTC
