### ISSUE TITLE
 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

### ISSUE THREAD

**Issue by vick16ach** [kristerkari/react-native-svg-transformer#108] opened 2020-09-24 07:27 UTC
I just followed the tutorial and got this error.

All i have is 
```
package.json

"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.11.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3"
  },
```

```
login.js

import React, {Component} from 'react';
import {Text, View} from 'react-native';
import Logo from '../assets/images/logo-white.svg';

class Login extends Component {
  render() {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <Logo />
        <Text>Hello, world!</Text>
      </View>
    );
  }
}

export default Login;
```

```
Error i got is below ,

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

Check the render method of `Login`.

This error is located at:
    in RCTView (at View.js:34)
    in View (at login.js:8)
    in Login (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:150)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:221)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:220)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:563)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:545)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:539)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:535)
    in RCTView (at View.js:34)
    in View (at Card.tsx:529)
    in Card (at CardContainer.tsx:189)
    in CardContainer (at CardStack.tsx:558)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:69)
    in MaybeScreen (at CardStack.tsx:551)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:48)
    in MaybeScreenContainer (at CardStack.tsx:461)
    in CardStack (at StackView.tsx:458)
    in KeyboardManager (at StackView.tsx:456)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:453)
    in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
    in GestureHandlerRootView (at StackView.tsx:452)
    in StackView (at createStackNavigator.tsx:84)
    in StackNavigator (at navigation.js:12)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:390)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at navigation.js:11)
    in MyStack (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

Tried everything but couldn't be able to solve it. I'm not using EXPO. Kindly anyone help me.

**Comment by lyseiha** [comment] 2020-09-30 07:46
https://github.com/kristerkari/react-native-svg-transformer/issues/29#issuecomment-670301147

**Comment by kristerkari** [comment] 2020-09-30 10:01
Like @lyseiha mentioned, most likely your configuration file (`metro.config.js`) is not setup correctly.

**Comment by kristerkari** [comment] 2020-10-08 14:34
Closing this since there seem to be no further discussion about the problem, and it might already be solved.

**Closed by kristerkari** 2020-10-08 14:34 UTC

**Comment by vlad-dewitt** [comment] 2021-01-11 21:08
Same problem in iOS release variant. It works in debug, but not in release. When I'm trying to log the component, as example 
```
import Logo from "logo.svg"
console.log(Logo)
```
It shows 5, number.... 
Any solution ?

**Comment by lanke96** [comment] 2021-01-14 00:12
I won't work for me either, and I tried the solution given in #29. I don't know what else to do.

**Comment by CarbonyDK** [comment] 2021-01-18 00:36
> Same problem in iOS release variant. It works in debug, but not in release. When I'm trying to log the component, as example 
> 
> ```
> 
> import Logo from "logo.svg"
> 
> console.log(Logo)
> 
> ```
> 
> It shows 5, number.... 
> 
> Any solution ?

Same issue. In debug mode all is ok but ios release version crashes. I'm using yarn workspaces monorepo.

**Comment by kristerkari** [comment] 2021-01-18 13:40
@vlad-dewitt @lanke96 @CarbonyDK Is anyone of you able to provide me some kind of repository or the code how to reproduce the problem? It's very difficult to pinpoint what the problem might be just based on the information here.

**Comment by vlad-dewitt** [comment] 2021-01-18 13:48
@kristerkari, I have yarn workspaces project with two RN apps. The file structure is the same for any yarn workspaces repo:
packages
|-app1
|-app2
|-shared

My configurations for both 2 apps in the metro.config.js:
`const blacklist = require('metro-config/src/defaults/blacklist')
const { getDefaultConfig } = require("metro-config")
const path = require('path')

module.exports = (async() => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig()

  return {
    projectRoot: __dirname,
    watchFolders: [
      path.resolve(__dirname, "../../")
    ],
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer"),
      assetPlugins: ['expo-asset/tools/hashAssetFiles'],
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      })
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"],
      extraNodeModules: {
        '@xdoctor-app/shared': path.resolve(__dirname, "../shared")
      },
      blacklistRE: blacklist([
        /ios\/Pods\/.*/,
        /(.*\/android\/React(Android|Common)\/.*|.*\/versioned-react-native\/.*|node_modules\/react\/dist\/.*|website\/node_modules\/.*|heapCapture\/bundle\.js|.*\/__tests__\/.*)$/
      ])
    },
    server: {
      enhanceMiddleware: (middleware) => {
        return (req, res, next) => {
          const assetsPath = '/shared/assets/'
          const otherAssetsPath = '/node_modules/'

          if (req.url.startsWith(assetsPath)) {
            req.url = req.url.replace(assetsPath, '/assets/../shared/assets/')
          }

          if (req.url.startsWith(otherAssetsPath)) {
            req.url = req.url.replace(otherAssetsPath, '/assets/../../node_modules/')
          }

          return middleware(req, res, next)
        }
      }
    }
  }
})()`

Everything is ok on Android in debug and release apks, and everything work fine in XCode debug build, but not in the release, as I said earlier the imported svg becomes a number, like any other asset file.

**Comment by CarbonyDK** [comment] 2021-01-18 14:17
> @kristerkari, I have yarn workspaces project with two RN apps. The file structure is the same for any yarn workspaces repo:
> 
> packages
> 
> |-app1
> 
> |-app2
> 
> |-shared
> 
> 
> 
> My configurations for both 2 apps in the metro.config.js:
> 
> ```
> 
> const blacklist = require('metro-config/src/defaults/blacklist')
> 
> const { getDefaultConfig } = require("metro-config")
> 
> const path = require('path')
> 
> 
> 
> module.exports = (async() => {
> 
>   const {
> 
>     resolver: { sourceExts, assetExts }
> 
>   } = await getDefaultConfig()
> 
> 
> 
>   return {
> 
>     projectRoot: __dirname,
> 
>     watchFolders: [
> 
>       path.resolve(__dirname, "../../")
> 
>     ],
> 
>     transformer: {
> 
>       babelTransformerPath: require.resolve("react-native-svg-transformer"),
> 
>       assetPlugins: ['expo-asset/tools/hashAssetFiles'],
> 
>       getTransformOptions: async () => ({
> 
>         transform: {
> 
>           experimentalImportSupport: false,
> 
>           inlineRequires: false
> 
>         }
> 
>       })
> 
>     },
> 
>     resolver: {
> 
>       assetExts: assetExts.filter(ext => ext !== "svg"),
> 
>       sourceExts: [...sourceExts, "svg"],
> 
>       extraNodeModules: {
> 
>         '@my-app/shared': path.resolve(__dirname, "../shared")
> 
>       },
> 
>       blacklistRE: blacklist([
> 
>         /ios\/Pods\/.*/,
> 
>         /(.*\/android\/React(Android|Common)\/.*|.*\/versioned-react-native\/.*|node_modules\/react\/dist\/.*|website\/node_modules\/.*|heapCapture\/bundle\.js|.*\/__tests__\/.*)$/
> 
>       ])
> 
>     },
> 
>     server: {
> 
>       enhanceMiddleware: (middleware) => {
> 
>         return (req, res, next) => {
> 
>           const assetsPath = '/shared/assets/'
> 
>           const otherAssetsPath = '/node_modules/'
> 
> 
> 
>           if (req.url.startsWith(assetsPath)) {
> 
>             req.url = req.url.replace(assetsPath, '/assets/../shared/assets/')
> 
>           }
> 
> 
> 
>           if (req.url.startsWith(otherAssetsPath)) {
> 
>             req.url = req.url.replace(otherAssetsPath, '/assets/../../node_modules/')
> 
>           }
> 
> 
> 
>           return middleware(req, res, next)
> 
>         }
> 
>       }
> 
>     }
> 
>   }
> 
> })()
> 
> ```
> 
> 
> 
> Everything is ok on Android in debug and release apks, and everything works fine in XCode debug build, but not in the release, as I said earlier the imported svg becomes a number, like any other asset file.

@kristerkari I have the same environment configuration, but without expo. Maybe we have problem with relative path when ios release process wants to transform svgs in project? Or our metro-config doesn't triggered in release mode.. I think this is problem with yarn workspaces config or path config..

**Comment by vlad-dewitt** [comment] 2021-01-18 14:24
@kristerkari, this is ejected expo app, bare react native. I also tested if the config isn't triggered, but if I change any of these configurations, then the release version of the application crashes

**Comment by kristerkari** [comment] 2021-01-19 07:30
> Maybe we have problem with relative path when ios release process wants to transform svgs in project?

Hmm... that's possible yeah

**Comment by CarbonyDK** [comment] 2021-01-19 09:42
> Hmm... that's possible yeah

However I don't know how to configure that. @kristerkari  Can you check it with blank yarn workspaces project?

**Comment by Mantisimo** [comment] 2021-01-25 14:47
Same issue for me
Not using Expo, IOS variant.

    "react-native": "0.63.3",
    "react-native-svg": "^12.1.0",
    "react-native-svg-transformer": "^0.14.3",


```
import DefaultLogo from '../../../assets/images/default-logo.svg';
```

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: number.

```
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig(__dirname);

  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          babelTransformerPath: require.resolve('react-native-svg-transformer')
        },
        resolver: {
          assetExts: assetExts.filter((ext) => ext !== 'svg'),
          sourceExts: [...sourceExts, 'svg']
        }
      })
    }
  };
})();


```

**Comment by hugoh59** [comment] 2021-01-27 17:17
Same issue in RN 0.63.4, never used expo.

**Comment by vlad-dewitt** [comment] 2021-01-30 11:08
metro bundler and these packages are dog shit, all tender and unreliable, just a shame...

**Comment by cinemanja** [comment] 2021-03-01 15:33
I have the same issue even with the new metro.config.js file structure. RN version 0.63.4

**Comment by MahmoudAziz1996** [comment] 2021-06-12 22:13
add the configuration to metro.config.js:

`const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();`

**Comment by samih7** [comment] 2021-07-13 20:46
@hugoh59 @kurovskyi @vlad-dewitt Any chance you guys found a solution?

Facing the exact same issue using a NX monorepo (iOS release mode fails).

**Comment by samih7** [comment] 2021-07-14 09:45
> @hugoh59 @kurovskyi @vlad-dewitt Any chance you guys found a solution?
> 
> Facing the exact same issue using a NX monorepo (iOS release mode fails).

Fixed it by moving `metro.config.js` at the root level instead of `apps/my-app/`.

**Comment by kurovskyi** [comment] 2021-07-14 10:07
> > @hugoh59 @kurovskyi @vlad-dewitt Any chance you guys found a solution?
> 
> > 
> 
> > Facing the exact same issue using a NX monorepo (iOS release mode fails).
> 
> 
> 
> Fixed it by moving `metro.config.js` at the root level instead of `apps/my-app/`.

Thanks, I will try it soon and give feedback.

**Comment by sagarkm** [comment] 2022-03-17 11:29
> > @hugoh59 @kurovskyi @vlad-dewitt Any chance you guys found a solution?
> > Facing the exact same issue using a NX monorepo (iOS release mode fails).
> 
> Fixed it by moving `metro.config.js` at the root level instead of `apps/my-app/`.

This worked for me as well. 
Wonder why the nx react-native default project places metro.config.js within apps/my-app/.

**Comment by FrenzyNwoba** [comment] 2022-07-10 23:34
For React Native 0.68.2, 

> npm i react-native-svg 
> npm i react-native-svg-transformer 


Delete every line of metro.config.js file. 

Then paste this inside: (Then Rebuild your app!)

> 
> ```
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> const { getDefaultConfig } = require('metro-config');
> 
> module.exports = (async () => {
>   const {
>     resolver: { sourceExts, assetExts },
>   } = await getDefaultConfig();
>   return {
>     transformer: {
>       babelTransformerPath: require.resolve('react-native-svg-transformer'),
>       getTransformOptions: async () => ({
>         transform: {
>           experimentalImportSupport: false,
>           inlineRequires: true,
>         },
>       }),
>     },
>     resolver: {
>       assetExts: assetExts.filter((ext) => ext !== 'svg'),
>       sourceExts: [...sourceExts, 'svg'],
>     },
>   };
> })();
> ```

This worked for me... 🥂
