### ISSUE TITLE
Not working with RN 0.63.4

### ISSUE THREAD

**Issue by sandropoluan** [kristerkari/react-native-svg-transformer#121] opened 2021-01-28 09:24 UTC
Everything is set but got this error
`Invariant Violation: View config getter callback for component `<svg ....</svg>` must be a function (received `undefined`).`

**Comment by kristerkari** [comment] 2021-01-30 13:13
Hi @sandropoluan. I'm using the transformer with 0.63.4 and it's working fine, so it might be that there is something wrong with the SVG image that you are trying to import.

**Comment by DooaRashidAnsari** [comment] 2021-02-08 12:09
I am also having same issue with same version of RN

**Comment by kristerkari** [comment] 2021-02-08 12:13
@DooaRashidAnsari do you have an example of the thing that throws an error for you? It's really hard to help if you just say that you have the same problem.

**Comment by RatebSeirawan** [comment] 2021-02-10 11:24
I'm having a similar issue with RN 0.63.4, it was working perfectly on previous RN versions, after further debugging 
the app just instantly crash on runtime, the error message that I'm receiving is on the native side 
`Thread 1: "*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil"`

Weirdly enough it only happens when the .svg file is big, if I remove the big svg files it works all of a sudden, in my project im importing over 600 kb of svgs, the file that I removed is 36 kb in a single svg this resolved the issue and the app won't crash after removing the big svg, I hope this helps to resolve the issue, for the record am using latest versions of RN and RN-svg and react-native-svg-transformer of the time I've submitted this comment

**Comment by kristerkari** [comment] 2021-02-26 11:16
> I'm having a similar issue with RN 0.63.4, it was working perfectly on previous RN versions, after further debugging
> the app just instantly crash on runtime, the error message that I'm receiving is on the native side
> `Thread 1: "*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil"`

Just wanted to clear this up: this error is a native side error, so the problem that you encountered is most likely on the `react-native-svg` side.

**Comment by kristerkari** [comment] 2021-02-26 11:17
I'm closing this issue because it seems to just be a collection separate problems, and there is no code to reproduce any errors.

**Closed by kristerkari** 2021-02-26 11:17 UTC

**Comment by jailsonpaca** [comment] 2021-05-14 20:07
I solve this problem with expo r -c
