### ISSUE TITLE
0.12.0 - application freezes while rendering SVG

### ISSUE THREAD

**Issue by XenorPLxx** [kristerkari/react-native-svg-transformer#3] opened 2018-11-24 16:32 UTC
Hey,

Thanks for great work on the svg-transformer!

After upgrade from 0.11.3 to 0.12.0 my application freezes when I'm navigating to screen, that contains imported SVG.

Tested on React Native 0.57.5.

Example SVG, that app freezes on, below:

```
<svg width="30px" height="52px" viewBox="0 0 30 52" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="-6.16521421%" y1="14.7934649%" x2="100%" y2="91.4270586%" id="linearGradient-1">
            <stop stop-color="#FAA461" offset="0%"></stop>
            <stop stop-color="#F75C1C" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="ONBOARDING-FULL" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="000-B" transform="translate(-287.000000, -462.000000)" fill="url(#linearGradient-1)">
            <g id="smartphone-(1)" transform="translate(287.000000, 462.000000)">
                <path d="M16.411208,47.8814655 C16.411208,48.6383688 15.7792968,49.2521215 15,49.2521215 C14.2207032,49.2521215 13.588792,48.6383688 13.588792,47.8814655 C13.588792,47.1245623 14.2207032,46.5108095 15,46.5108095 C15.7792968,46.5108095 16.411208,47.1245623 16.411208,47.8814655 Z M3.46153846,9.18965517 L26.5384615,9.18965517 L26.5384615,41.8017241 L3.46153846,41.8017241 L3.46153846,9.18965517 Z M26.3076923,0 C28.3458533,0.00218884138 29.9977464,1.60661374 30,3.5862069 L30,48.4137931 C29.9977464,50.3933863 28.3458533,51.9978112 26.3076923,52 L3.69230769,52 C1.65414669,51.9978112 0.0022536,50.3933863 0,48.4137931 L0,3.5862069 C0.0022536,1.60661374 1.65414669,0.00218884138 3.69230769,0 L26.3076923,0 Z M9.80769231,2.9137931 C9.29792665,2.9137931 8.88461538,3.31522761 8.88461538,3.81034483 C8.88461538,4.30546204 9.29792665,4.70689655 9.80769231,4.70689655 L20.1923077,4.70689655 C20.7020733,4.70689655 21.1153846,4.30546204 21.1153846,3.81034483 C21.1153846,3.31522761 20.7020733,2.9137931 20.1923077,2.9137931 L9.80769231,2.9137931 Z M15,51.045225 C16.7983775,51.0430362 18.2551082,49.6281655 18.2573618,47.8814655 C18.2573618,46.1343278 16.7988282,44.7177061 15,44.7177061 C13.2011718,44.7177061 11.7426382,46.1343278 11.7426382,47.8814655 C11.7426382,49.6286032 13.2011718,51.045225 15,51.045225 Z M28.3846154,42.6982759 L28.3846154,8.29310345 C28.3846154,7.79798623 27.9713041,7.39655172 27.4615385,7.39655172 L2.53846154,7.39655172 C2.02869588,7.39655172 1.61538462,7.79798623 1.61538462,8.29310345 L1.61538462,42.6982759 C1.61538462,43.1933931 2.02869588,43.5948276 2.53846154,43.5948276 L27.4615385,43.5948276 C27.9713041,43.5948276 28.3846154,43.1933931 28.3846154,42.6982759 Z" id="Combined-Shape"></path>
            </g>
        </g>
    </g>
</svg>
```

**Comment by kristerkari** [comment] 2018-11-25 20:14
Thanks! I switched to using SVGR in the latest version, so maybe there is a bug. 

I’ll investigate using the svg that you provided.

**Comment by kristerkari** [comment] 2018-11-26 03:01
I tested your svg and it is working for me on Android. I don't have access to a Mac currently, so I can not test if it works on iOS. 

Does the image crash the app on both iOS and Android, or just iOS? Would it be possible for you to provide the code that you use in addition to the svg image?

**Comment by XenorPLxx** [comment] 2018-11-26 09:40
I've investigated further by creating simple example app https://github.com/XenorPLxx/svg-transformer-test and it works here on both iOS and Android.

Sadly, I can't share code of the problematic app, but I'll investigate further and try to find out what exactly causes this issue to pop up.

I'll let you know when I'll find something.

**Comment by kristerkari** [comment] 2018-11-26 14:46
Thanks for having a look at the issue! Are you using the latest version of `react-native-svg` in your project? Also check that you have purged all caches (npm included) for the app when you are running it.

**Comment by XenorPLxx** [comment] 2018-11-27 15:06
Hello again!

I've managed to reproduce error.
I've had some more icons in my tab bar navigation that I've forgot about and it seems these are causing problems. These are just regular FontAwesome5 icons wrapped in some gradient.

Here's example that doesn't work on both iOS and Android:
https://github.com/XenorPLxx/svg-transformer-test/commit/958c16fbf6cdcdaae40a5c42de146d8d4c968f4e

**Comment by kristerkari** [comment] 2018-11-27 19:10
Okay, with that svg image I can reproduce the bug. Seems to be something related to the `font-family`, `font-size`, etc. attributes on the `g` element that causes it to crash.

I need to check how to fix this later, but for now you can use v0.11.3.

**Comment by XenorPLxx** [comment] 2018-11-27 19:31
I don't really need those tags, it's just a result of dirty copy from Sketch. If it's only these that cause problems then I'll remove them and upgrade to 0.12.0 :). Thanks!

**Comment by kristerkari** [comment] 2018-11-28 18:20
I think that I managed to find the bug that causes the crash. I have posted a new issue to SVGR's repo:
https://github.com/smooth-code/svgr/issues/243

Let's wait and see what the response is.

**Comment by kristerkari** [comment] 2018-11-29 19:45
I made another PR, this time to `react-native-svg` to get the bug fixed:
https://github.com/react-native-community/react-native-svg/pull/860

**Comment by dl-husky73** [comment] 2019-07-18 14:12
Hi, I am new to SVG but have it transformer and react-native-svg working.   Building a dashboard and received all new art yesterday.  The SVG's with numbers in them (with font-weight) are crashing the android app while the svg's without the text work.   Is there a workaround?

**Comment by kristerkari** [comment] 2019-07-18 19:48
@dl-husky73 There is no workaround currently, this is something that should be fixed in `react-native-svg` project, but a proper fix requires quite a lot of work.

**Comment by kristerkari** [comment] 2019-08-05 07:03
This is now fixed in the latest `react-native-svg` version.

**Closed by kristerkari** 2019-08-05 07:03 UTC
Labels: Bug 🐛
