### ISSUE TITLE
Some svg images not transformed properly

### ISSUE THREAD

**Issue by rimzici** [kristerkari/react-native-svg-transformer#23] opened 2019-05-16 08:09 UTC
First of all thanks for the great work! Was very helpful and I must say it works for most of the images that I use in my app, except for one.

Here is a reproducible [demo](https://github.com/rimzici/SVGTransform)

**FYI: There are some semi-transparent objects in this svg.**

Any help will be appreciated.
Thanks!

react: 16.8.3
react-native: 0.59.8
react-native-svg: ^9.4.0
react-native-svg-transformer: ^0.13.0

**Comment by kristerkari** [comment] 2019-05-16 17:23
Thanks @rimzici!

The problem is either in `SVGR` or `react-native-svg`. Usually the problem is that `react-native-svg` does not yet fully support everything that you can do with SVG images.

I'll have a look to see what is the thing that is not working.

**Comment by kristerkari** [comment] 2019-05-16 18:58
I had a quick look, and it seems that the problem is related to the `x` and `y` coordinates that the SVG is using. It's rendered correctly with a Web browser, but not in `react-native-svg`.

If I change the first two numbers of the `viewBox` property to `0` and change the `x` and `y` values from the elements inside the SVG images, things start to appear.

**Comment by rimzici** [comment] 2019-05-17 04:26
Thanks for the quick response @kristerkari  !

May be I should use a simpler svg and dig into the issue later.

**Comment by kristerkari** [comment] 2019-05-22 16:54
Alright, good to know, closing as resolved.

**Closed by kristerkari** 2019-05-22 16:54 UTC
