### ISSUE TITLE
SVGR no longer works on iOS release build after upgraded to RN 0.63.0

### ISSUE THREAD

**Issue by stackia** [kristerkari/react-native-svg-transformer#98] opened 2020-07-09 08:07 UTC
After upgrading to RN 0.63.0, on iOS release build, icons no longer fills with my customized color in .svgrrc.

But on iOS dev build, Android dev/release build it works well.

**Comment by kristerkari** [comment] 2020-07-13 20:09
Thanks, I need to check and verify this one.

**Comment by stackia** [comment] 2020-07-15 03:57
Looks like this is related to https://github.com/facebook/react-native/issues/29351, https://github.com/facebook/react-native/commit/a8e85026cfa60056b1bcbcd39cde789e4d65f9cb

`react-native bundle` will run from `ios` dir on RN 0.63. I added some `console.log` and found the transformer gets wrong relative paths when `react-native bundle` is launched from `ios` dir.

```diff
  if (filename.endsWith(".svg") || filename.endsWith(".svgx")) {
    var config = resolveConfig.sync(resolveConfigDir(filename));
+    console.log(filename, config);
```

Output:

```text
✘ stackia@MacBook-2020  ~/Repositories/xxx/packages/my-rn-app/ios   feat/rn-0.63  ../node_modules/.bin/react-native bundle --entry-file ./index.js --bundle-output ./result.bundle --assets-dest ./bundle-assets --platform ios
                 Welcome to React Native!
                Learn once, write anywhere


transform[stdout]: ../design/src/components/Logo/logo-icon.svg null
transform[stdout]: ../design/src/components/Logo/logo-text.svg null
```

I have a monorepo structure, the real relative path of these files should be:

```text
../../design/src/components/Logo/logo-icon.svg
../../design/src/components/Logo/logo-text.svg
```

If I run `react-native bundle` in my RN app root dir, the SVGR config resolves correctly.

As a workaround, adding `cd $PROJECT_DIR/..` as said in https://github.com/facebook/react-native/issues/29351#issuecomment-657906376 will force `react-native bundle` to run in app root dir instead of `ios` dir.

**Comment by kristerkari** [comment] 2020-07-15 07:06
So is this a bug or a feature in RN 0.63? It seems like people are reporting that the bundling is not working for them, so I guess that this might get fixed in a patch?

**Comment by stackia** [comment] 2020-07-16 08:51
> So is this a bug or a feature in RN 0.63? It seems like people are reporting that the bundling is not working for them, so I guess that this might get fixed in a patch?

It's a feature that allows `react-native` cli to run from project sub-directories. Before 0.63, `react-native` cli could only be started from project root. Now it can be started from `ios` / `android` directory (and RN 0.63 by default will run `react-native bundle` from the `ios` directory). https://github.com/facebook/react-native/commit/a8e85026cfa60056b1bcbcd39cde789e4d65f9cb

**Comment by Aung-Myint-Thein** [comment] 2020-07-16 14:09
I am having the issue on Android after updating to RN 0.63.1 .. any work around? Thanks!

**Comment by kristerkari** [comment] 2020-07-16 14:33
Sorry for being slow with this @stackia. From the linked commits it seems that this is caused by a small feature on iOS, but in reality it breaks all 3rd party transformer plugins for React Native.

Before making any fixes, I want make sure that I understand what the problem is and what is a correct fix for it. For now I would recommend to stick with React Native 0.62 instead of the new 0.63 until I can be sure that PR #99 is the correct way to apply the fix for all of the libraries that I have published.

**Comment by Aung-Myint-Thein** [comment] 2020-07-19 04:58
Weird.. In some of my devices, the svg is showing up. In some of the devices, it show up sometimes. The behaviour is not very consistent. Could there be some config issue?

**Comment by bjackson** [comment] 2020-07-27 03:25
FWIW, I have the same issue on 0.62.2 and in dev.,

My react-native-svg-transformer version is 0.14.3, and my react-native-svg version is 12.1.0.

My .svgrrc:
```
{
  "replaceAttrValues": {
    "#fff": "{props.fill}"
  }
}
```

My metro.config.js:
```
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg']
    }
  };
})();
```

**Comment by kristerkari** [comment] 2020-07-27 09:51
So, I'm currently waiting for someone from the React Native team to comment somethin on these open issues & PR, and I'll release a new version of the transformer with a fix if it's not getting fixed in React Native.

Issues: 
https://github.com/facebook/react-native/issues/29351, https://github.com/facebook/react-native/issues/29356

PR:
https://github.com/facebook/react-native/pull/29477

**Comment by jmunozDevsu** [comment] 2020-09-15 23:26
any news about this?

**Comment by kristerkari** [comment] 2020-09-23 08:17
@jmunozDevsu It looks like this got fixed in React Native, but there hasn't been a new version yet: https://github.com/facebook/react-native/pull/29477

**Comment by kristerkari** [comment] 2020-09-30 09:59
I haven't had time to try out yet, but this issue should be fixed in the latest 0.63.3 patch version:
https://github.com/facebook/react-native/releases/tag/v0.63.3

**Comment by kristerkari** [comment] 2020-10-15 09:59
Closing since this has been fixed in React Native version 0.63.3. Please update to that patch version.

**Closed by kristerkari** 2020-10-15 09:59 UTC

**Comment by facuescobar** [comment] 2023-07-31 19:10
I just upgraded to  "react-native": "0.72.3", and I have the same problem.

**declarations.d.ts**
```js
declare module '*.svg' {
  import React from 'react';
  import {SvgProps} from 'react-native-svg';
  const content: React.FC<SvgProps>;
  export default content;
}
```

**metro.config.js**
```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

const config = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: true,
        },
      }),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg', 'cjs'],
      resolveRequest: (context, moduleName, platform) => {
        if (moduleName.startsWith('graphql-request')) {
          return {
            filePath: `${__dirname}/node_modules/graphql-request/build/esm/index.js`,
            type: 'sourceFile',
          };
        }

        return context.resolveRequest(context, moduleName, platform);
      },
    },
  };
})();

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

**package.json**
```
   "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-svg": "^13.10.0",
    "react-native-svg-transformer": "^1.1.0",
```

**Comment by ugar0ff** [comment] 2024-01-19 09:04
@facuescobar  did you find a solution?

**Comment by itsnyx** [comment] 2025-08-05 23:40
Im using rn 0.79.5 and this svgrrc not working in ios!
